from __future__ import annotations

from html import escape
from pathlib import Path


def _value(value, suffix: str = "") -> str:
    return "—" if value is None else f"{value}{suffix}"


def write_html_report(manifest: dict[str, object], path: Path) -> None:
    rows: list[str] = []
    for day in manifest.get("days", []):
        fuel = day.get("fuel", {})
        elevation = day.get("elevation", {})
        warning = fuel.get("warning") or ""
        rows.append(
            "<tr>"
            f"<td>{day['day']}</td>"
            f"<td>{escape(str(day['name']))}</td>"
            f"<td>{_value(round(day['distance_m'] / 1000, 1) if day.get('distance_m') else None, ' km')}</td>"
            f"<td>{_value(round(day['duration_s'] / 3600, 1) if day.get('duration_s') else None, ' h')}</td>"
            f"<td>{_value(elevation.get('max_elevation_m'), ' m')}</td>"
            f"<td>{_value(fuel.get('range_utilisation_percent'), '%')}</td>"
            f"<td>{escape(str(warning))}</td>"
            "</tr>"
        )
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(str(manifest['route_id']))} expedition report</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:1200px;margin:2rem auto;padding:0 1rem;color:#202124}}
h1{{margin-bottom:.25rem}} .muted{{color:#666}} table{{border-collapse:collapse;width:100%;margin-top:1.5rem}}
th,td{{border:1px solid #ddd;padding:.65rem;text-align:left;vertical-align:top}}th{{background:#f5f5f5}}
.cards{{display:flex;gap:1rem;flex-wrap:wrap;margin-top:1rem}}.card{{border:1px solid #ddd;border-radius:.5rem;padding:1rem;min-width:160px}}
</style></head><body>
<h1>{escape(str(manifest['route_id']))}</h1><p class="muted">Generated by Route Builder</p>
<div class="cards"><div class="card"><strong>Days</strong><br>{manifest.get('day_count', 0)}</div>
<div class="card"><strong>Total distance</strong><br>{_value(round(manifest['total_distance_m']/1000,1) if manifest.get('total_distance_m') else None,' km')}</div>
<div class="card"><strong>POIs</strong><br>{manifest.get('poi_count', 0)}</div></div>
<table><thead><tr><th>Day</th><th>Route</th><th>Distance</th><th>Ride time</th><th>Highest entered elevation</th><th>Fuel range used</th><th>Fuel warning</th></tr></thead>
<tbody>{''.join(rows)}</tbody></table>
<p class="muted">Fuel and elevation values are planning aids based on entered data. Verify road access, fuel availability, weather, permits and local conditions independently.</p>
</body></html>"""
    path.write_text(html, encoding="utf-8")
